# Generated by Django 4.2.7 on 2025-12-21 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deletion_failed', 'Deletion Failed')], default='pending', max_length=20)),
                ('ingestion_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('partial', 'Partial'), ('complete', 'Complete'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('deletion_failed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='files_filea_user_id_3fd6fe_idx'), models.Index(fields=['user', 'ingestion_status'], name='files_filea_user_id_ae2fec_idx')],
            },
        ),
    ]
