# Generated by Django 4.2.7 on 2025-12-21 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField()),
                ('extraction_method', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('image_vision', 'Image Vision'), ('image_vision_failed', 'Image Vision Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.fileasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['file', 'chunk_index'],
                'indexes': [models.Index(fields=['user', 'file'], name='rag_documen_user_id_813ffb_idx'), models.Index(fields=['file', 'chunk_index'], name='rag_documen_file_id_47014e_idx')],
            },
        ),
    ]
