# Generated by Django 4.2.7 on 2025-12-22 19:41

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1024),
        ),
    ]
